# Generated by Kaixa from Kaixa.toml. Do not edit.
if(KAIXA_CMAKE_DEPENDENCIES_INCLUDED)
    return()
endif()
set(KAIXA_CMAKE_DEPENDENCIES_INCLUDED TRUE)
include(FetchContent)
if(POLICY CMP0169)
    cmake_policy(SET CMP0169 OLD)
endif()

set(BUILD_GMOCK ON CACHE INTERNAL "Set by Kaixa" FORCE)
set(INSTALL_GTEST OFF CACHE INTERNAL "Set by Kaixa" FORCE)
set(gtest_force_shared_crt OFF CACHE INTERNAL "Set by Kaixa" FORCE)
FetchContent_Declare(kaixa_package_2
    GIT_REPOSITORY [[https://github.com/google/googletest.git]]
    GIT_TAG [[52eb8108c5bdec04579160ae17225d66034bd723]]
)
FetchContent_GetProperties(kaixa_package_2)
if(NOT kaixa_package_2_POPULATED)
    FetchContent_Populate(kaixa_package_2)
endif()
set(_kaixa_package_2_source "${kaixa_package_2_SOURCE_DIR}")
add_subdirectory("${_kaixa_package_2_source}" "${CMAKE_BINARY_DIR}/_kaixa/googletest" EXCLUDE_FROM_ALL)
if(NOT TARGET googletest)
    add_library(googletest INTERFACE)
    target_link_libraries(googletest INTERFACE GTest::gtest_main)
endif()

set(BENCHMARK_ENABLE_TESTING OFF CACHE INTERNAL "Set by Kaixa" FORCE)
set(BENCHMARK_ENABLE_GTEST_TESTS OFF CACHE INTERNAL "Set by Kaixa" FORCE)
set(BENCHMARK_ENABLE_WERROR OFF CACHE INTERNAL "Set by Kaixa" FORCE)
set(BENCHMARK_ENABLE_INSTALL OFF CACHE INTERNAL "Set by Kaixa" FORCE)
set(BENCHMARK_INSTALL_DOCS OFF CACHE INTERNAL "Set by Kaixa" FORCE)
FetchContent_Declare(kaixa_package_3
    GIT_REPOSITORY [[https://github.com/google/benchmark.git]]
    GIT_TAG [[eddb0241389718a23a42db6af5f0164b6e0139af]]
)
FetchContent_GetProperties(kaixa_package_3)
if(NOT kaixa_package_3_POPULATED)
    FetchContent_Populate(kaixa_package_3)
endif()
set(_kaixa_package_3_source "${kaixa_package_3_SOURCE_DIR}")
add_subdirectory("${_kaixa_package_3_source}" "${CMAKE_BINARY_DIR}/_kaixa/google_benchmark" EXCLUDE_FROM_ALL)
if(NOT TARGET google_benchmark)
    add_library(google_benchmark INTERFACE)
    target_link_libraries(google_benchmark INTERFACE benchmark::benchmark_main)
endif()
target_compile_options(benchmark PRIVATE [[$<$<COMPILE_LANG_AND_ID:CXX,Clang,AppleClang>:-Wno-c2y-extensions>]])
target_compile_options(benchmark_main PRIVATE [[$<$<COMPILE_LANG_AND_ID:CXX,Clang,AppleClang>:-Wno-c2y-extensions>]])

